export const ARTISAN_CATEGORIES = [
  "Bougie",
  "Sublimation",
  "Couture",
  "Personnalisation",
  "Bois",
  "Bijoux",
  "Céramique",
  "Papeterie",
  "Gravure laser",
  "Impression 3D",
  "Crochet",
  "Enfants",
  "Résine",
  "Beauté",
  "Alimentaire",
  "Art",
] as const;
